### NumPy Arrays

In [4]:
my_list = [1,2,3]

In [5]:
import numpy as np

In [6]:
arr = np.array(my_list) #1D array

In [7]:
arr

array([1, 2, 3])

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(my_mat) #2D array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.linspace(0,5,10) #1D array - one bracket ']''

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [19]:
np.eye(4) #Identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(5,5)

array([[0.80349686, 0.71342086, 0.37970063, 0.99238079, 0.355472  ],
       [0.87923254, 0.59714921, 0.73399334, 0.22297862, 0.09511712],
       [0.09870381, 0.09793927, 0.38363829, 0.70493176, 0.99973379],
       [0.18455436, 0.71270434, 0.57376194, 0.75455106, 0.83370569],
       [0.63428966, 0.63892252, 0.00848427, 0.75420037, 0.87387546]])

In [21]:
np.random.randn(2)

array([-0.96584384, -0.61100923])

In [22]:
np.random.randn(2,2)

array([[-1.16174701,  0.04530955],
       [ 1.64462028,  0.1137506 ]])

In [23]:
np.random.randint(1,100)

14

In [24]:
np.random.randint(1,100,10)

array([34, 59, 38, 44,  7, 25, 56, 74, 42, 49])

In [30]:
ranarr = np.random.randint(1,50,25)

In [31]:
ranarr

array([35, 13, 19, 14, 35, 34, 11, 16, 46, 24,  3, 10, 31, 45,  2, 27, 34,
        5, 29, 23, 23, 44,  9, 46, 21])

In [33]:
ranarr.reshape(5,5)

array([[35, 13, 19, 14, 35],
       [34, 11, 16, 46, 24],
       [ 3, 10, 31, 45,  2],
       [27, 34,  5, 29, 23],
       [23, 44,  9, 46, 21]])

In [35]:
ranarr.max()

46

In [36]:
ranarr.min()

2

In [37]:
ranarr.argmax() #index of max value

8

In [39]:
ranarr.argmin() # index of min value

14

In [40]:
ranarr.shape #1D

(25,)

In [41]:
arr = ranarr.reshape(5,5)

In [42]:
arr.shape #2D

(5, 5)

In [43]:
arr.dtype

dtype('int64')

### NumPy Indexing and Selection

In [44]:
import numpy as np

In [45]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr[8]

8

In [47]:
arr[3:8]

array([3, 4, 5, 6, 7])

In [48]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [49]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [51]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [52]:
arr[0:5] = 100

In [53]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [56]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [59]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [60]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [64]:
arr_copy = arr.copy() #original array doesn't change

In [62]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [65]:
arr_copy[:] = 100

In [66]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [67]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [71]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]]) #two ']' brackets
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [72]:
arr_2d[0][0]

5

In [73]:
arr_2d[0]

array([ 5, 10, 15])

In [74]:
arr_2d[2,1]

40

In [75]:
arr_2d[1,2]

30

In [76]:
arr_2d[1][2]

30

In [78]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [81]:
bool_arr = arr > 15

In [82]:
bool_arr

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False])

In [83]:
arr[bool_arr]

array([99, 99, 99, 99, 99, 99])

In [84]:
arr[arr>5]

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [85]:
arr[arr<3]

array([], dtype=int64)

In [86]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [87]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [88]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

### Numpy Operations

In [89]:
import numpy as np

In [90]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [92]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [93]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [94]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [95]:
1/0

ZeroDivisionError: division by zero

In [96]:
arr / arr

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [97]:
1 / arr #inf - infinity

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [98]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [99]:
#univarsal array functions

In [100]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [101]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [102]:
np.max(arr)

10

In [103]:
arr.max()

10

In [104]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [105]:
np.log(arr)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])